NDefines.NGame.START_DATE = "2018.1.1.12"
NDefines.NGame.END_DATE = "2100.1.1.1"

NDefines.NDiplomacy.VOLUNTEERS_TRANSFER_SPEED = 14
NDefines.NDiplomacy.VOLUNTEERS_DIVISIONS_REQUIRED = 1
NDefines.NDiplomacy.TENSION_TIME_SCALE_START_DATE = "2018.1.1.12"
NDefines.NDiplomacy.TENSION_CB_WAR = 10

NDefines.NCountry.MIN_SURRENDER_LIMIT = 0.1

NDefines_Graphics.NGraphics.VICTORY_POINT_MAP_ICON_AFTER = {0, 10}

NDefines.NResistance.INITIAL_HISTORY_COMPLIANCE = 100