NDefines.NGame.START_DATE = "2018.1.1.12"
NDefines.NGame.END_DATE = "2100.1.1.1"

NDefines.NDiplomacy.VOLUNTEERS_TRANSFER_SPEED = 14
NDefines.NDiplomacy.VOLUNTEERS_DIVISIONS_REQUIRED = 2
NDefines.NDiplomacy.TENSION_TIME_SCALE_START_DATE = "2018.1.1.12"
NDefines.NDiplomacy.TENSION_CB_WAR = 10
NDefines.NDiplomacy.IDEOLOGY_JOIN_FACTION_MIN_LEVEL = 0

NDefines.NCountry.MIN_SURRENDER_LIMIT = 0.1
NDefines.NCountry.BASE_STABILITY_PARTY_POPULARITY_FACTOR = 0
NDefines.NCountry.DEFAULT_STABILITY = 0.35
NDefines.NCountry.BASE_RESEARCH_SLOTS  = 1

NDefines_Graphics.NGraphics.VICTORY_POINT_MAP_ICON_AFTER = {0, 5}
NDefines_Graphics.NGraphics.COUNTRY_FLAG_TEX_MAX_SIZE = 2048
NDefines_Graphics.NGraphics.COUNTRY_FLAG_SMALL_TEX_MAX_SIZE = 1024
NDefines_Graphics.NGraphics.GRADIENT_BORDERS_THICKNESS_COUNTRY_LOW = 4.0
NDefines_Graphics.NGraphics.GRADIENT_BORDERS_THICKNESS_COUNTRY_HIGH = 14.0

NDefines.NResistance.INITIAL_HISTORY_COMPLIANCE = 100

NDefines.NPolitics.BASE_POLITICAL_POWER_INCREASE = 1

NDefines.NAI.DIPLOMACY_FACTION_WRONG_IDEOLOGY_PENALTY = 0
NDefines.NAI.DIPLOMACY_FACTION_SAME_IDEOLOGY_MAJOR = 5