NDefines.NGame.START_DATE = "2018.1.1.12"
NDefines.NGame.END_DATE = "2100.1.1.1"

NDefines.NDiplomacy.VOLUNTEERS_TRANSFER_SPEED = 14
NDefines.NDiplomacy.VOLUNTEERS_DIVISIONS_REQUIRED = 1
NDefines.NDiplomacy.TENSION_TIME_SCALE_START_DATE = "2018.1.1.12"
NDefines.NDiplomacy.TENSION_CB_WAR = 10
NDefines.NDiplomacy.IDEOLOGY_JOIN_FACTION_MIN_LEVEL = 0

NDefines.NCountry.MIN_SURRENDER_LIMIT = 0.1
NDefines.NCountry.BASE_STABILITY_PARTY_POPULARITY_FACTOR = 0
NDefines.NCountry.DEFAULT_STABILITY = 0.2

NDefines_Graphics.NGraphics.VICTORY_POINT_MAP_ICON_AFTER = {0, 10}
NDefines_Graphics.NGraphics.COUNTRY_FLAG_TEX_MAX_SIZE = 2048
NDefines_Graphics.NGraphics.COUNTRY_FLAG_SMALL_TEX_MAX_SIZE = 1024

NDefines.NResistance.INITIAL_HISTORY_COMPLIANCE = 100

NDefines.NAI.DIPLOMACY_FACTION_WRONG_IDEOLOGY_PENALTY = 0
NDefines.NAI.DIPLOMACY_FACTION_SAME_IDEOLOGY_MAJOR = 5